/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.otus;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class HelloOtusTest {
    @Test void appHasAGreeting() {
        HelloOtus classUnderTest = new HelloOtus();
        assertEquals("Hello, World!", classUnderTest.getGreeting());
    }
}
