/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.otus;

import com.google.common.base.Joiner;

public class HelloOtus {
    public String getGreeting() {
        Joiner joiner = Joiner.on(" ").skipNulls();
        return joiner.join("Hello,", null, "World!");
    }

    public static void main(String[] args) {
        System.out.println(new HelloOtus().getGreeting());
    }
}
